config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index", as: :home
  resources :curriculums
  resources :camp_instructors
  resources :locations
  resources :camps
  resources :instructors
  
  get '/about', :to => 'home#about'
  get '/contact', :to => 'home#contact'
  get '/privacy', :to => 'home#privacy'

end

app/models/curriculum.rb
class Curriculum < ApplicationRecord
  # relationships
  has_many :camps

  # validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  ratings_array = [0] + (100..3000).to_a
  validates :min_rating, numericality: { only_integer: true }, inclusion: { in: ratings_array }
  validates :max_rating, numericality: { only_integer: true }, inclusion: { in: ratings_array }
  validate :max_rating_greater_than_min_rating

  # scopes
  scope :alphabetical, -> { order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :for_rating, ->(rating) { where("min_rating <= ? and max_rating >= ?", rating, rating) }


  private
  def max_rating_greater_than_min_rating
    return true if self.max_rating.nil? || self.min_rating.nil?
    unless self.max_rating > self.min_rating
      errors.add(:max_rating, "must be greater than the minimum rating")
    end
  end


end

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController
  before_action :set_curriculum, only: [:show, :edit, :update, :destroy]

  def index
    @curriculums = Curriculum.all
  end

  def show
    @past_camps_using = @curriculum.camps.past.chronological
    @upcoming_camps_using = @curriculum.camps.upcoming.chronological
  end

  def edit
  end

  def new
    @curriculum = Curriculum.new
  end

  def create
    @curriculum = Curriculum.new(curriculum_params)
    if @curriculum.save
      redirect_to curriculum_path(@curriculum), notice: "#{@curriculum.name} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    @curriculum.update(curriculum_params)
    if @curriculum.save
      redirect_to curriculum_path(@curriculum), notice: "#{@curriculum.name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @curriculum.destroy
    redirect_to curriculums_url, notice: "#{@curriculum.name} was removed from the system."
  end

  private
    def set_curriculum
      @curriculum = Curriculum.find(params[:id])
    end

    def curriculum_params
      params.require(:curriculum).permit(:name, :description, :min_rating, :max_rating, :active)
    end
end

app/views/curriculums/_curriculum_details.html.erb
<h3> Curriculum Details</h3>

<p>
  <strong>Name:</strong>
  <%= @curriculum.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @curriculum.description %>
</p>

<p>
  <strong>Ratings:</strong>
  <%= @curriculum.min_rating == 0 ? "Unrated" : @curriculum.min_rating %> - <%= @curriculum.max_rating %>
</p>


<p>
  <strong>Active:</strong>
  <%= @curriculum.active ? "Yes" : "No" %>
</p>

app/views/curriculums/_form.html.erb
<%= simple_form_for(@curriculum) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="form-inputs">
      <%= f.input :name, label_html: { class: 'active' } %>
      <%= f.input :min_rating, label_html: { class: 'active' } %>
      <%= f.input :max_rating, label_html: { class: 'active' } %>
      <%= f.input :description, label_html: { class: 'active' } %>
      <%= f.input :active %>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col s8">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/curriculums/edit.html.erb
<h1>Editing Curriculum</h1>

<%= render 'form', curriculum: @curriculum %>

<%= link_to 'Show', @curriculum %> |
<%= link_to 'Back', curriculums_path %>

app/views/curriculums/index.html.erb
<p id="notice"><%= notice %></p>

<% if @curriculums.empty? %>
  <h3>There are no curriculums in the system at this time</h3>
<% else %>
  <h3>Curriculums</h3>

  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ratings</th>
      <th>Times Used</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @curriculums.each do |curriculum| %>
      <tr>
        <td><%= link_to curriculum.name, curriculum %></td>
        <td><%= curriculum.min_rating == 0 ? "Unrated" : curriculum.min_rating %> - <%= curriculum.max_rating %></td>
        <td><%= Camp.for_curriculum(curriculum.id).size %></td>
        <td><%= link_to 'Edit', edit_curriculum_path(curriculum), :class=>"btn waves-effect waves-light blue" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

    <% end %>

<%= link_to 'New curriculum', new_curriculum_path %>

app/views/curriculums/new.html.erb
<h1>New curriculum</h1>

<%= render 'form', curriculum: @curriculum %>

<%= link_to 'Back', curriculums_path %>

app/views/curriculums/show.html.erb
<div class="row">
  <div class="col s5">
    <%= render :partial => "curriculum_details" %>
  </div>
  <div class="col s7">
    <%= render :partial => "partials/camps_list", locals: {camps: @past_camps_using, state: "Past"} unless @past_camps_using.empty? %>
    <%= render :partial => "partials/camps_list", locals: {camps: @upcoming_camps_using, state: "Upcoming"} %>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <%= render :partial => "partials/object_options", locals: {model_name: "curriculum", object: @curriculum} %>
  </div>
</div>